# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_wsprstats.ui',
# licensing of 'UI_wsprstats.ui' applies.
#
# Created: Sat Apr  6 19:57:02 2019
#      by: pyside2-uic  running on PySide2 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(689, 614)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tblStats = QtWidgets.QTableView(self.centralwidget)
        self.tblStats.setGeometry(QtCore.QRect(30, 271, 631, 291))
        self.tblStats.setObjectName("tblStats")
        self.tblStats.horizontalHeader().setDefaultSectionSize(65)
        self.gbSpotsByDates = QtWidgets.QGroupBox(self.centralwidget)
        self.gbSpotsByDates.setGeometry(QtCore.QRect(30, 11, 251, 201))
        self.gbSpotsByDates.setObjectName("gbSpotsByDates")
        self.rbAllDates = QtWidgets.QRadioButton(self.gbSpotsByDates)
        self.rbAllDates.setGeometry(QtCore.QRect(20, 20, 82, 17))
        self.rbAllDates.setChecked(True)
        self.rbAllDates.setObjectName("rbAllDates")
        self.rbLast7Days = QtWidgets.QRadioButton(self.gbSpotsByDates)
        self.rbLast7Days.setGeometry(QtCore.QRect(20, 60, 82, 17))
        self.rbLast7Days.setObjectName("rbLast7Days")
        self.rbLast30Days = QtWidgets.QRadioButton(self.gbSpotsByDates)
        self.rbLast30Days.setGeometry(QtCore.QRect(20, 80, 82, 17))
        self.rbLast30Days.setObjectName("rbLast30Days")
        self.rbDateRange = QtWidgets.QRadioButton(self.gbSpotsByDates)
        self.rbDateRange.setGeometry(QtCore.QRect(20, 100, 101, 17))
        self.rbDateRange.setObjectName("rbDateRange")
        self.gbDateRange = QtWidgets.QGroupBox(self.gbSpotsByDates)
        self.gbDateRange.setEnabled(True)
        self.gbDateRange.setGeometry(QtCore.QRect(120, 100, 121, 80))
        self.gbDateRange.setTitle("")
        self.gbDateRange.setObjectName("gbDateRange")
        self.label_3 = QtWidgets.QLabel(self.gbDateRange)
        self.label_3.setGeometry(QtCore.QRect(4, 1, 47, 13))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.gbDateRange)
        self.label_4.setGeometry(QtCore.QRect(6, 40, 47, 13))
        self.label_4.setObjectName("label_4")
        self.dteFrom = QtWidgets.QDateTimeEdit(self.gbDateRange)
        self.dteFrom.setEnabled(True)
        self.dteFrom.setGeometry(QtCore.QRect(3, 14, 111, 22))
        self.dteFrom.setObjectName("dteFrom")
        self.dteTo = QtWidgets.QDateTimeEdit(self.gbDateRange)
        self.dteTo.setGeometry(QtCore.QRect(3, 53, 111, 22))
        self.dteTo.setObjectName("dteTo")
        self.rbPreviousDay = QtWidgets.QRadioButton(self.gbSpotsByDates)
        self.rbPreviousDay.setEnabled(True)
        self.rbPreviousDay.setGeometry(QtCore.QRect(20, 40, 82, 17))
        self.rbPreviousDay.setChecked(False)
        self.rbPreviousDay.setAutoRepeat(True)
        self.rbPreviousDay.setObjectName("rbPreviousDay")
        self.gbTotalsByCategory = QtWidgets.QGroupBox(self.centralwidget)
        self.gbTotalsByCategory.setGeometry(QtCore.QRect(300, 11, 251, 91))
        self.gbTotalsByCategory.setObjectName("gbTotalsByCategory")
        self.rbNoCategory = QtWidgets.QRadioButton(self.gbTotalsByCategory)
        self.rbNoCategory.setGeometry(QtCore.QRect(20, 20, 121, 17))
        self.rbNoCategory.setChecked(True)
        self.rbNoCategory.setObjectName("rbNoCategory")
        self.rbByReporterTransmitterBand = QtWidgets.QRadioButton(self.gbTotalsByCategory)
        self.rbByReporterTransmitterBand.setGeometry(QtCore.QRect(20, 40, 201, 17))
        self.rbByReporterTransmitterBand.setObjectName("rbByReporterTransmitterBand")
        self.rbByBand = QtWidgets.QRadioButton(self.gbTotalsByCategory)
        self.rbByBand.setGeometry(QtCore.QRect(20, 60, 82, 17))
        self.rbByBand.setObjectName("rbByBand")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(30, 216, 251, 40))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.pbQuit = QtWidgets.QPushButton(self.groupBox_2)
        self.pbQuit.setGeometry(QtCore.QRect(10, 10, 75, 23))
        self.pbQuit.setObjectName("pbQuit")
        self.pbCollectData = QtWidgets.QPushButton(self.groupBox_2)
        self.pbCollectData.setGeometry(QtCore.QRect(160, 10, 75, 23))
        self.pbCollectData.setObjectName("pbCollectData")
        self.lwConfigInfo = QtWidgets.QListWidget(self.centralwidget)
        self.lwConfigInfo.setEnabled(False)
        self.lwConfigInfo.setGeometry(QtCore.QRect(300, 110, 251, 145))
        self.lwConfigInfo.setAutoFillBackground(False)
        self.lwConfigInfo.setFrameShape(QtWidgets.QFrame.Box)
        self.lwConfigInfo.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lwConfigInfo.setObjectName("lwConfigInfo")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 689, 21))
        self.menubar.setObjectName("menubar")
        self.menu_Quit = QtWidgets.QMenu(self.menubar)
        self.menu_Quit.setObjectName("menu_Quit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_Quit = QtWidgets.QAction(MainWindow)
        self.action_Quit.setObjectName("action_Quit")
        self.menu_Quit.addAction(self.action_Quit)
        self.menubar.addAction(self.menu_Quit.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.gbSpotsByDates.setTitle(QtWidgets.QApplication.translate("MainWindow", "Spots by Dates", None, -1))
        self.rbAllDates.setText(QtWidgets.QApplication.translate("MainWindow", "All Dates", None, -1))
        self.rbLast7Days.setText(QtWidgets.QApplication.translate("MainWindow", "Last 7 Days", None, -1))
        self.rbLast30Days.setText(QtWidgets.QApplication.translate("MainWindow", "Last 30 Days", None, -1))
        self.rbDateRange.setText(QtWidgets.QApplication.translate("MainWindow", "By Date Range", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MainWindow", "From", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("MainWindow", "To", None, -1))
        self.dteFrom.setDisplayFormat(QtWidgets.QApplication.translate("MainWindow", "yyyy-MM-dd HH:mm", None, -1))
        self.dteTo.setDisplayFormat(QtWidgets.QApplication.translate("MainWindow", "yyyy-MM-dd HH:mm", None, -1))
        self.rbPreviousDay.setText(QtWidgets.QApplication.translate("MainWindow", "Previous Day", None, -1))
        self.gbTotalsByCategory.setTitle(QtWidgets.QApplication.translate("MainWindow", "Totals by Category", None, -1))
        self.rbNoCategory.setText(QtWidgets.QApplication.translate("MainWindow", "No Categories", None, -1))
        self.rbByReporterTransmitterBand.setText(QtWidgets.QApplication.translate("MainWindow", "By Reporter, Transmitter, and Band", None, -1))
        self.rbByBand.setText(QtWidgets.QApplication.translate("MainWindow", "Band", None, -1))
        self.pbQuit.setText(QtWidgets.QApplication.translate("MainWindow", "&Quit", None, -1))
        self.pbCollectData.setText(QtWidgets.QApplication.translate("MainWindow", "&Collect Data", None, -1))
        self.menu_Quit.setTitle(QtWidgets.QApplication.translate("MainWindow", "&File", None, -1))
        self.action_Quit.setText(QtWidgets.QApplication.translate("MainWindow", "&Quit", None, -1))

